# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Location Name', max_length=100)),
                ('spotipy_client_id', models.CharField(help_text='Client ID for Spotipy', max_length=100)),
                ('spotipy_client_secret', models.CharField(help_text='Client Secret for Spotipy', max_length=100)),
                ('spotipy_redirect_uri', models.CharField(help_text='Redirect URI for Spotipy', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(help_text='Song Name', max_length=100)),
                ('song_artist', models.CharField(help_text='Song Artist', max_length=100)),
                ('time', models.CharField(help_text='Time the song was added to the queue', max_length=20)),
                ('location', models.ForeignKey(help_text='Location of Queue', on_delete=django.db.models.deletion.CASCADE, to='music.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Student ID', max_length=10)),
                ('song_name', models.CharField(help_text='Song Name', max_length=100)),
                ('song_artist', models.CharField(help_text='Song Artist', max_length=100)),
                ('location', models.ForeignKey(help_text='Location of Request', on_delete=django.db.models.deletion.CASCADE, to='music.Location')),
            ],
        ),
    ]
