# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20181117_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='location',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='time',
        ),
        migrations.AddField(
            model_name='queue',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
