# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20181117_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='id',
        ),
        migrations.AlterField(
            model_name='queue',
            name='song_URI',
            field=models.CharField(help_text='URI of a track', max_length=100, primary_key=True, serialize=False),
        ),
    ]
