# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_location_spotify_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='queue',
            name='song_URI',
            field=models.CharField(help_text='URI of a track', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='queue',
            unique_together=set([('location', 'song_URI')]),
        ),
    ]
